<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Гараж №11 на САМОХВАЛе</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f2f2f2;
      color: #333;
    }
    header {
      background-color: #222;
      color: #fff;
      padding: 20px 10px;
      text-align: center;
    }
    header h1 {
      margin: 0;
      font-size: 1.8em;
    }
    .container {
      padding: 15px;
      max-width: 800px;
      margin: auto;
    }
    .images img {
      width: 100%;
      height: auto;
      margin-bottom: 10px;
      border-radius: 5px;
    }
    .info {
      background: #fff;
      padding: 15px;
      margin-bottom: 15px;
      border-radius: 5px;
    }
    .info h2 {
      font-size: 1.2em;
      margin-top: 0;
    }
    .contacts a {
      display: inline-block;
      margin-right: 10px;
      text-decoration: none;
      color: #007bff;
    }
    .contacts a:hover {
      text-decoration: underline;
    }
    .map {
      margin-top: 15px;
    }
    .whatsapp-button {
      display: block;
      width: 100%;
      text-align: center;
      background-color: #25D366;
      color: white;
      padding: 15px;
      border: none;
      border-radius: 5px;
      font-size: 1.2em;
      text-decoration: none;
      margin-top: 15px;
    }
    footer {
      text-align: center;
      font-size: 0.9em;
      color: #aaa;
      margin: 30px 0 10px;
    }
  </style>
</head>
<body>
  <header>
    <h1>Гараж №11 на САМОХВАЛе</h1>
    <p>Автотовары во Владимире</p>
  </header>
  <div class="container">
    <div class="images">
      <img src="1.webp" alt="Фасад ТЦ САМОХВАЛ">
      <img src="2.webp" alt="Коридор внутри ТЦ">
    </div>

    <div class="info">
      <h2>О нас</h2>
      <p>Продажа автотоваров: дворники, свечи, автолампы, компрессоры, аксессуары, дефлекторы, сопутствующие товары.</p>
    </div>

    <div class="info">
      <h2>Доставка</h2>
      <p>Самовывоз из секции №11 ТЦ САМОХВАЛ. По городу доставка на следующий день по наличию.</p>
    </div>

    <div class="info contacts">
      <h2>Контакты</h2>
      <p>📞 Игорь: <a href="tel:+79056114608">+7 905 611 4608</a> — <a href="https://wa.me/79056114608">WhatsApp</a> / Telegram<br>
      📞 Михаил: <a href="tel:+79050575848">+7 905 057 5848</a> — <a href="https://wa.me/79050575848">WhatsApp</a><br>
      ✉️ Email: <a href="mailto:zhukov68@gmail.com">zhukov68@gmail.com</a></p>
    </div>

    <div class="info">
      <h2>Режим работы</h2>
      <p>Пн-Пт: 10:00–18:30<br>
      Сб-Вс: 10:00–16:30</p>
    </div>

    <a class="whatsapp-button" href="https://wa.me/79056114608" target="_blank">Написать в WhatsApp</a>

    <div class="map">
      <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A01a384373eab727ddfb96d1c3deea2b6b2cce1ab78005456a1ff916d7427ee50&amp;source=constructor" width="100%" height="300" frameborder="0"></iframe>
    </div>
  </div>

  <footer>
    © Гараж №11 на САМОХВАЛе, Владимир
  </footer>
</body>
</html>
